# Generated by Django 4.1 on 2022-08-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='regdate',
            field=models.CharField(max_length=30),
        ),
    ]
