# Generated by Django 4.1 on 2022-08-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0004_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
