# Generated by Django 4.1 on 2022-09-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0005_remove_login_id_alter_login_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmname', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=50)),
                ('jobdesc', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('salarypa', models.IntegerField()),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
    ]
