# Generated by Django 4.1 on 2022-09-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0006_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='emailaddress',
            field=models.EmailField(default='ok', max_length=50),
            preserve_default=False,
        ),
    ]
